### ISSUE TITLE
ビルド系のコマンド「rebuild/clean」について

### ISSUE THREAD

**Issue by robotmaidSirius** [kimushun1101/ros2-aliases#1]
ビルドしたフォルダを消したいタイミングがあって「rebuild」や「clean」コマンドがあると助かります。

消したいと思うタイミングですがPythonパッケージでパラメータを追加するためlaunchファイルでファイル名を書き間違うと「ファイルが無いんだけど？」と警告を発するときが多いです。

私は```ros2 build --cmake-clean-first```か、.colconフォルダを丸ごと消すことが多いです。
消す際は「Y/N」があると事故は少なる気がします。

**Comment by kimushun1101** [comment]
ありがとうございます。
https://github.com/kimushun1101/ros2-aliases/blob/706a76b9ac39ab6f9eedd169af26442b2b987afe/ros2_aliases.bash#L93

これでうまく行かないときに--cmake-clean-first できると便利そうです！
Y/N も含めて実装してみましたが以下のような形ではいかがでしょうか？

https://github.com/kimushun1101/ros2-aliases/blob/706a76b9ac39ab6f9eedd169af26442b2b987afe/ros2_aliases.bash#L107-L119

**Comment by robotmaidSirius** [comment]
実装ありがとうございます。
入力として、未記入/n/no/NO/nO/y/yes/Yes/YYESで試してみて動作できることを確認できました。
