### ISSUE TITLE
「ros2 topic pub ...」でyamlファイルを渡すコマンドが欲しい

### ISSUE THREAD

**Issue by robotmaidSirius** [kimushun1101/ros2-aliases#3]
テスト用に``` ros2 topic pub [...] topic_name message_type [values]```でデータを送信することがあるのですが[value]を書き間違うことが多いのでYAMLファイルで動作させたいです。
 
 ---
 
## サンプル

私は下記のシェルで同様の機能を再現してます。

 ```bash
 # ros2pub.sh topic_name message_type yaml_file [argument]
 
CMD_TOPIC_NAME=$1
CMD_MESSAGE_TYPE=$2
CMD_YAML_FILE=`cat $3
CMD_OPTIONS=$4

ros2 topic pub ${CMD_OPTIONS} ${CMD_TOPIC_NAME} ${CMD_MESSAGE_TYPE} "${CMD_YAML_FILE}"
```

**Comment by kimushun1101** [comment]
サンプルの提示ありがとうございます。
そのサンプルだとCMD_TOPIC_NAME やCMD_MESSAGE_TYPE、CMD_OPTIONS の入力で補完が効かないため、fzf による検索が有効であると思われます。
しかしながら個人的には、ros2 topic pub はTab 補完がros2 topic list などとは異なり1画面に収まるため、特にfzf で検索する必要もないかなと思い実装しませんでした。
例えば、頭の中で`/cmd_vel` をパブリッシュしたいと思ったときに、 
`ros2 topic pub /cmd_vel [Tab]` で
```
-1                             --qos-depth                    --spin-time
geometry_msgs/msg/Twist        --qos-durability               -t
--keep-alive                   --qos-history                  --times
-n                             --qos-profile                  --use-sim-time
--node-name                    --qos-reliability              -w
--once                         -r                             --wait-matching-subscriptions
-p                             --rate                         
--print                        -s 
```
と出して、型の確認もできますし、
`ros2 topic pub /cmd_vel geometry_msgs/msg/Twist [Tab]` で
```
-1
--keep-alive
linear:\^J\ \ x:\ 0.0\^J\ \ y:\ 0.0\^J\ \ z:\ 0.0\^Jangular:\^J\ \ x:\ 0.0\^J\ \ y:\ 0.0\^J\ \ z:\ 0.0\
-n
--node-name
--once
-p
--print
--qos-depth
--qos-durability
--qos-history
--qos-profile
--qos-reliability
-r
--rate
-s
--spin-time
-t
--times
--use-sim-time
-w
--wait-matching-subscriptions
```
と出て、`ros2 topic pub /cmd_vel geometry_msgs/msg/Twist li[Tab]` で、
```
 ros2 topic pub /cmd_vel geometry_msgs/msg/Twist linear:\
\ \ x:\ 0.0\
\ \ y:\ 0.0\
\ \ z:\ 0.0\
angular:\
\ \ x:\ 0.0\
\ \ y:\ 0.0\
\ \ z:\ 0.0\ 
```
ここまで補完されます。

YAML でトピックサンプルを渡すことができそうなのは初めて知りました。
ただし、複数の候補を別YAML で取っておくのであれば、それごとにros2 topic pub のコマンドを収めたシェルスクリプトを置いていてもファイル数としては変わりません。
YAML ファイルの値を少し変えて再実行したい場合においても、history から履歴を呼び出して微調整するのとそこまで労力が変わらないのかな？とも思いました。

ご質問やコメント等あれば追記をお願いいたします。

**Comment by robotmaidSirius** [comment]
TOPICをTABで補完についてありがとうございます。
補完できるので作成する際は[TAB]を利用したほうが良い気がしました。

> YAML ファイルの値を少し変えて再実行したい場合においても、history から履歴を呼び出して微調整するのとそこまで労力が変わらないのかな？とも思いました。

YAMLを渡す手段が欲しい理由ですが下記のサンプルのコードを書くことがあります。
送信間隔は長くなるのですがtest.yamlを上書きすることで任意のタイミングで数値を変更して動作を制御してました。

* test.yaml

```file
data: 1.0
```

* loop_pub.sh

```bash
for i in {1..100}; do
    CMD_YAML_FILE=`cat test.yaml`
    ros2 topic pub --once /test_topic std_msgs/msg/Float64 "${CMD_YAML_FILE}";
done
```

---

ここまで書いて思ったのですが、valueのYAMLファイルだけじゃなくてpub以下のオプションやtopic_name などをすべて内包したYAMLなりJSONファイルを取り込む方が利便性が高い気がしました。

機能拡張の近くaliasesとは程遠い内容のため、本Issueは***Close***で構わないでしょうか。

* sample_pub_parameter.yaml

```file
option: 
    --once
topic_name: 
    /test_topic
message_type: 
    std_msgs/msg/Float64
values: 
    data:
        1.0
```

**Comment by kimushun1101** [comment]
ご意見ありがとうございました。私としても大変勉強になりました。
一旦クローズしますが、本件で新たなアイディアがありましたらいつでもreopen してください。
