### ISSUE TITLE
コマンド「ros2 pkg executables」のaliasesが欲しいです。

### ISSUE THREAD

**Issue by robotmaidSirius** [kimushun1101/ros2-aliases#4]
ビルド成功後に実行可能なパッケージを探すため```ros2 pkg executables```を利用するのでexecutablesの欲しいです

**Comment by kimushun1101** [comment]
こんな感じでいかがでしょう？
引数やオプションはありますか？
https://github.com/kimushun1101/ros2-aliases/blob/8c780c026c6ed6a41876d2482d3d4e9f26564ade/ros2_aliases.bash#L142-L143

**Comment by robotmaidSirius** [comment]
実装ありがとうございます。
動作確認できました！

executablesは```--full-path```がありますが```-h```をつければ利用者は探索可能だと思うので特に必要無いくこのままで良いと思います。
